language: node_js
node_js:
- '0.10'
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
before_script:
- npm install
- jspm install
env:
  global:
    secure: xHF5bMMWru19PQvO0XDEX54wrdM38EU1UIShk6qkTaeHmn0arkl/v4nuLv1PLwezPQMWNSeChbuQiZOqch6henmjA7Z6zA4iyfSSo0PgpVGXqefcoPGHeeMX4CagRQ0zulntSxyQIFEQVNIAvOqMD3GYwH3LKC8kWws89kl/mxooKoAPxFsB4XZSXM8EOAuV+aPfXTuQyg6CdpNDkrM+QPSNpcIR11EvheM50C2cI7rYWUk4JXYLdKgTYcGBGM/gXIRrLPjQFtHxHV1PmWaC31DX8xPWIxjlX6IPaMzMzx3ejlQrqoeB5RoSZno5dJHvkzMbKMBHPbAyZsxqNPK/AhEca574AUGSjCIQn3+TmiODbM+CyDAs4OaeRL1+IH/x7KZSfmwR2Vrk06bIvuZuZaO1xNABvFN3FNSKt9V7PfEUtstDgWJO9jua20t+hgDvQeAqHh+/G8vVem/V+avvo/Vj75OpusocsGuKMnIyILn8YR1CG6YzoGlu6TiitDph9wDXGCNpXiUMwC5MdJL7/ap2C2QE2SF9l+aQK6mJFbzPch3cGGk7SRQJLpD4Iz4lW06gqWBnpgTRp1hOnumPkE0QbK9Yxtz2nKqvg/+N05R/bNZnN9mKzRThQAeW0piA8f7wXxP40EDVYvZL0EZBW1fu/ivibmK5FXWkPn9aHFM=
